workflows:
  web-build-&-deploy:
    name: Web build
    max_build_duration: 60
    environment:
      flutter: beta
      xcode: latest
      cocoapods: default
    scripts:
      - flutter packages pub get
      - flutter config --enable-web
      - name: Build Web
        script: |
          flutter build web --release
          cd build/web
          7z a -r ../web.zip ./*
    artifacts:
      - build/web.zip
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - mishraaditya595@gmail.com