name: Flutter

on:  #events (push and pull_request)
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:   #here we specify the jobs - We could have multiple jobs
  build:  #name it something meaningful 
    runs-on: ubuntu-latest   #runner: select a machine to use

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.1'
          channel: 'stable'
      
      - name: Activate flutterfire
        run: curl -sL https://firebase.tools | bash
      - run: dart pub global activate flutterfire_cli
      - run: flutterfire configure --project=$PROJECT --platforms="android" --ios-bundle-id=$IOS_BUNDLE_ID --android-package-name=$ANDROID_PACKAGE_NAME -y
      - name: Build Debug APK
        run: flutter build apk --debug
      - run: ls build/app/outputs/flutter-apk
      # - run: ls build/app/outputs/bundle/release
